### PR TITLE
fix: cleanup unnecessary edge case inclusions of `DFC`

### LINKED ISSUE #281: Lua error
**Describe the bug**
1x ...rfaceLFGBulletinBoard/GroupBulletinBoard.lua:147: attempt to index field '?' (a nil value)
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:147: in function `FilterDungeon'
[string "@LFGBulletinBoard/RequestList.lua"]:867: in function `ParseMessage'
[string "@LFGBulletinBoard/GroupBulletinBoard.lua"]:845: in function `?'
[string "@LFGBulletinBoard/LibGPIToolBox.lua"]:119: in function <LFGBulletinBoard/LibGPIToolBox.lua:116>

Locals:
dungeon = "DFC"
isHeroic = false
isRaid = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
GBB = <table> {
 GetLfgList = <function> defined @LFGBulletinBoard/LfgToolList.lua:133
 CreateTagList = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:392
 GetDungeonNames = <function> defined @LFGBulletinBoard/Dungeons.lua:12
 ClearNeeded = false
 InitGroupList = <function> defined @LFGBulletinBoard/GroupList.Lua:177
 TBCMAXDUNGEON = 32
 LfgRequestHideTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:727
 tagList = <table> {
 }
 GetSortedDungeonKeys = <function> defined @LFGBulletinBoard/dungeons/classic.lua:273
 suffixTags = <table> {
 }
 LevelRange = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:129
 ParseMessage = <function> defined @LFGBulletinBoard/RequestList.lua:774
 LFG_Successfulljoined = true
 ClearTimer = 1752399386
 UpdateLfgToolNoSearch = <function> defined @LFGBulletinBoard/LfgToolList.lua:229
 NotifySound = 1210
 JoinLFG = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:195
 searchTagsLoc = <table> {
 }
 FoldAllDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:941
 ClickFrame = <function> defined @LFGBulletinBoard/RequestList.lua:981
 CreateChatFrame = <function> defined @LFGBulletinBoard/Chat.lua:3
 Initalized = true
 BtnClose = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:328
 MAXCOMPACTWIDTH = 350
 OnLoad = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:871
 WOTLKDUNGEONSTART = 33
 dungeonSecondTags = <table> {
 }
 rawClassicDungeonInfo = <table> {
 }
 Version = "3.33"
 TAGBAD = "---"
 GetCustomFilterKeys = <function> defined @LFGBulletinBoard/CustomCategories.lua:148
 GetDungeons = <function> defined @LFGBulletinBoard/RequestList.lua:584
 GetDungeonSort = <function> defined @LFGBulletinBoard/Dungeons.lua:729
 TBCDUNGEONSTART = 33
 heroicTagsLoc = <table> {
 }
 LocalizationInit = <function> defined @LFGBulletinBoard/Localization.lua:825
 Popup_Minimap = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:476
 ClickDungeon = <function> defined @LFGBulletinBoard/RequestList.lua:988
 Tool = <table> {
 }
 HeroicKeywords = <table> {
 }
 RequestShowTooltip = <function> defined @LFGBulletinBoard/RequestList.lua:1037
 OptionsInit = <function> defined @LFGBulletinBoard/Options.lua:280
 AllowInInstance = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:50
 MSGPREFIX = "LFG Bulletin Board: "
 UpdateLfgTool = <function> defined @LFGBulletinBoard/LfgToolList.lua:207
 OptionsUpdate = <function> defined @LFGBulletinBoard/Options.lua:113
 Announce = <function> defined @LFGBulletinBoard/Chat.lua:140
 LFG_UPDATETIME = 10
 LfgUpdateList = <function> defined @LFGBulletinBoard/LfgToolList.lua:489
 BtnSelectChannel = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:264
 GetCustomFilterNames = <function> defined @LFGBulletinBoard/CustomCategories.lua:198
 LfgRequestShowTooltip = <function> defined @LFGBulletinBoard/LfgToolList.lua:678
 GetRaids = <function> defined @LFGBulletinBoard/Dungeons.lua:702
 L = <table> {
 }
 ElapsedSinceListUpdate = 0.080000
 Init = <function> defined @LFGBulletinBoard/GroupBulletinBoard.lua:503
 ENDINGDUNGEONEND = 39
 SyncCustomFilterTags = <function> defined @LFGBulletinBoard/CustomCategories.lua:167
 RequestList = <table> {
 }
 ShouldReset = false
 LFG_Timer = 1720860707
 RaidList = <table> {
 }
 locales = <table> {
 }
 TBCDUNGE

**Desktop (please complete the following information):**
 - Version 3.34

### PR DESCRIPTION
**Pull request by juemrami**
**Related Issues**:
 - #281
 - #288
 - #289
 
 
**Changes**:
- `DFC` does not need to be have its dungeonSort index set to a decimal value. 
    - I believe the motivation for fractional dungeonSort values was so that the associated key would not get iterated over in any of the simple integer loops that used the `MAXDUNGEON` related variables.
- `DFC`'s name is defined in `dungeons/classic.lua` and does not need to be set in DefaultEnGB table
- `DFC` does not need to be disambiguated from `DM2` and `DM`.

### CODE REVIEW

File: LFGBulletinBoard/dungeons/classic.lua [hunk 1]
```diff
@@ -150,7 +150,7 @@ local infoOverrides = {
         size = 20,
     },
     -- Demon Fall Canyon
-    DFC = isSoD and {
+    DFC = {
```
Comment (juemrami) [inline LFGBulletinBoard/dungeons/classic.lua:153]: This ones a minor nit.

Because `DFC` is already conditionally added to the `LFGDungeonID`'s table, then if `isSoD==false` this check is never hit. 

The entries above this on, for Gnomer/BFD/ST, use the `isSoD` conditional to modify the original data provided for those dungeons. They are considered dungeons not raids and have a different level ranges in regular Classic Era, so the `isSoD` check is used to modify that data on SoD clients only.

File: LFGBulletinBoard/RequestList.lua [hunk 2]
```diff
@@ -691,11 +691,9 @@ function GBB.GetDungeons(msg,name)
 		if nameLevel>0 and nameLevel<40 then
 			dungeons["DM"]=true
 			dungeons["DM2"]=false
-			dungeons["DFC"]=false
 		else
 			dungeons["DM"]=false
 			dungeons["DM2"]=true
-			dungeons["DFC"]=true
```
Comment (juemrami) [inline LFGBulletinBoard/RequestList.lua:698]: This is causing errors outside of SoD, and Diremaul listings to organized under DFC in SoD

Comment (Vysci) [reply LFGBulletinBoard/RequestList.lua:698]: half the shit has been so long forgot what it was there for

File: LFGBulletinBoard/dungeons/classic.lua (hunk 1 above)
Comment (Vysci) [reply LFGBulletinBoard/dungeons/classic.lua:153]: Might be worth keeping as an extra safety check

**Review by Vysci — APPROVED** [review]

File: LFGBulletinBoard/dungeons/classic.lua [hunk 3]
```diff
@@ -149,7 +149,7 @@ local infoOverrides = {
         maxLevel = 60,
         size = 20,
     },
-    -- Demon Fall Canyon
+    -- Demon Fall Canyon (completely spoofed for SoD since its not added into the LFGDungeon db2 table)
     DFC = isSoD and {
```
Comment (juemrami) [inline LFGBulletinBoard/dungeons/classic.lua:153]: readded the check.
